nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - ghost

ghost:
  build: ghost
  ports:
    - "2368:2368"
  volumes_from:
    - content
  environment:
    - url=http://brage.switchbit.local.io

content:
  build: content
  command: echo "Ghost content volume"
