version: "2"

services:

  nginx-ghost-proxy-template:
    image: donovanmuller/nginx-ghost-proxy-template:1
    container_name: nginx-ghost-proxy-template
    command: echo "Ghost Nginx proxy configuration volume"

  letsencrypt-certs:
    image: busybox
    container_name: letsencrypt-certs
    volumes:
      - "/etc/nginx/certs"
    command: echo "Letsencrypt certificate volume"

  nginx-proxy:
    image: nginx:1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
        - letsencrypt-certs
        - nginx-ghost-proxy-template
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    volumes_from:
      - nginx-proxy
      - nginx-ghost-proxy-template
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  content:
    build: content
    container_name: ghost-content
    command: echo "Ghost content volume"

  ghost:
    build: ghost
    container_name: ghost
    volumes_from:
      - content
    environment:
      - VIRTUAL_HOST=?
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=2368
      - LETSENCRYPT_HOST=?
      - LETSENCRYPT_EMAIL=?
      - url=http://brage.switchbit.local.io
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
